language: node_js
node_js:
- '8'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn
  - yarn test
  - git checkout master && ./node_modules/.bin/lerna version --conventional-commits && ls && git log && git push

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
