language: node_js
node_js:
- '8'

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn install --pure-lockfile
  - yarn test
  - git reset --hard HEAD && git checkout master && ./node_modules/.bin/lerna version --conventional-commits --yes && ls && git log && git push

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
