language: node_js
node_js:
- '8'

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install
  
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: release
      if: branch = master
      script: git reset --hard HEAD && git checkout master && ./node_modules/.bin/lerna publish --conventional-commits --yes

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
