# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Main

on: [push]
#   release:
#     types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - name: Setup NPM & GitHub auth
        run: |
          cp ./scripts/.npmrc-ci .npmrc
          npm whoami
          npm whoami --registry https://npm.pkg.github.com
          git config --global user.name "BasaltBot"
          git config --global user.email "$GITHUB_EMAIL"
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Bump versions w Lerna; commit & push git changes
        run: ./node_modules/.bin/lerna version --conventional-commits --yes
      - name: GitHub Packages Publish
        run: ./node_modules/.bin/lerna publish from-git --registry https://npm.pkg.github.com --yes
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: NPM Publish
        run: ./node_modules/.bin/lerna publish from-git --yes
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
